install: rollback installation on failure
When the `cilium install` command fails, all Kubernetes object already
created by the installer are not automatically deleted. This causes
subsequent installation attempts to fail as some objects already exist:

    $ cilium install
    🔮 Auto-detected Kubernetes kind: GKE
    🔮 Auto-detected cluster name: gke-cilium-dev-europe-west4-a-jibi-cluster
    🔮 Auto-detected IPAM mode: kubernetes
    🔮 Auto-detected datapath mode: gke
    ✅ Detected GKE native routing CIDR: 10.32.0.0/14
    🚀 Creating Resource quotas...
    Error: Unable to install Cilium:  resourcequotas "cilium-resource-quota" already exists

This commit introduces additional logic to delete, in case the
installation fails, all the objects created during the installation
process:

    $ cilium install --config install-no-conntrack-iptables-rules=true
    ..
    ↩️ Rolling back installation...
    Error: Unable to install Cilium: cannot generate ConfigMap: --install-no-conntrack-iptables-rules cannot be enabled on Google GKE

    $ cilium install
    ..
    ⌛ Waiting for Cilium to be installed...

Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>